// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/Alkemic/gowroc-di-project/blog"
	"github.com/Alkemic/gowroc-di-project/handler"
	"github.com/Alkemic/gowroc-di-project/repository"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeHttpHandler() handler.HttpHandler {
	dbdsn := getDBDSN()
	db := openDB(dbdsn)
	postRepository := repository.NewRepository(db)
	blogService := blog.NewBlogService(postRepository)
	httpHandler := handler.NewHandler(blogService)
	return httpHandler
}
